name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
          registry-url: "https://npm.pkg.github.com"
      - name: install
        run: yarn install
      - name: test
        run: yarn run test
        env:
          CI: true
      - name: publish
        run: |
          npx can-npm-publish --verbose && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
